apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "thisChart.fullname" . }}
  labels:
    {{- include "thisChart.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.configMap.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
