apiVersion: v1
kind: Service
metadata:
  name: {{ template "thisChart.fullname" . }}
  labels:
    {{- include "thisChart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
  selector:
    {{- include "thisChart.selectorLabels" . | nindent 4 }}
